{% set name = "hatch-build" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hatch_build-{{ version }}.tar.gz
  sha256: 99c37a2373350a399407d49b7bac286faae4cb3e18409c126d16fedce4bafe90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - hatch-build = hatch_build.cli:hatchling

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - hatchling >=1.14.1,<1.15

test:
  imports:
    - hatch_build.cli
  commands:
    - pip check
    - hatch-build --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python-project-templates/hatch-build
  dev_url: https://github.com/python-project-templates/hatch-build
  summary: A minimal CLI wrapper around hatchling build
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
